server:
  port: 8070

spring:
  application:
    name: task-impl

  datasource:
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: classpath:database-changelog.xml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

jwt:
  secret: ${JWT_SECRET}

springdoc:
  show-login-endpoint: true
  show-pre-authorize: true

app:
  services:
    user-url: ${USER_SERVICE_URL:http://localhost:9000}
  kafka:
    notification-topic: "notification.message.in"
  scheduling:
    notification-cron: ${NOTIFICATION_CRON:0 * * * * *}
    batch-size: ${NOTIFICATION_BATCH_SIZE:5}
  security:
    technical-token: ${TECH_TOKEN}